version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ticket_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ticket_management
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  db_data: 